name: "Sungrow Inverter Addon"
version: "0.3.35"
slug: "sungrow"
description: "Sungrow Inverter Addon"
init: false
startup: application
boot: auto
url: "https://github.com/heinrich321/voyanti-sungrow/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  servers:
    - name: "Sungrow Inverter 1"
      ha_display_name: "SG1"
      serialnum: "A2340700442"
      server_type: "SUNGROW_INVERTER"
      connected_client: "Client1"
      modbus_id: 1
    - name: "Sungrow Logger 1"
      ha_display_name: "SGL1"
      serialnum: "B2391405111"
      server_type: "SUNGROW_LOGGER"
      connected_client: "Client1"
      modbus_id: 247
    - name: "Grid Meter"
      ha_display_name: "GM"
      serialnum: "unknown"
      server_type: "ACREL_METER"
      connected_client: "Client1"
      modbus_id: 2
  clients:
    - name: "ModbusTCP"
      ha_display_name: "Client1"
      type: "TCP"
      host: "10.0.0.15"
      port: 502
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt"
  mwtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "modbus"
schema:
  servers:
    - name: str
      ha_display_name: str
      serialnum: str
      server_type: list(SUNGROW_INVERTER|SUNGROW_LOGGER|ACREL_METER)
      connected_client: str
      modbus_id: int(0,255)
  clients:
    - name: str
      ha_display_name: str
      type: list(TCP|RTU)
      host: str?
      port: int?
      baudrate: int?
      bytesize: int?
      parity: bool?
      stopbits: int?
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mwtt_ha_discovery_topic: str
  mqtt_base_topic: str